#!/usr/bin/env bun
// Write the checksums, metadata, installer, and Homebrew formula for built release archives.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
	CHATGPT_ARCHIVE_NAME,
	HOMEBREW_TAP,
	REPOSITORY,
	RUNTIME_TARGETS,
	runtimeArchiveName,
	type RuntimeTarget,
} from "./release-targets";

export type ReleaseMetadata = {
	schemaVersion: 1;
	version: string;
	repository: string;
	artifacts: Record<RuntimeTarget, { file: string; sha256: string }>;
};

function downloadUrl(version: string, file: string): string {
	return `https://github.com/${REPOSITORY}/releases/download/v${version}/${file}`;
}

export function formula(metadata: ReleaseMetadata): string {
	const source = (target: RuntimeTarget) =>
		`url "${downloadUrl(metadata.version, metadata.artifacts[target].file)}"
      sha256 "${metadata.artifacts[target].sha256}"`;
	return `# Generated by ${REPOSITORY} scripts/release.ts. Do not edit this file in ${HOMEBREW_TAP}.
class Agentsims < Formula
  desc "Local multi-device simulator workspace for iOS and Android"
  homepage "https://agentsims.dev"
  version "${metadata.version}"
  license "Apache-2.0"

  on_macos do
    depends_on macos: :sonoma

    on_arm do
      ${source("darwin-arm64")}
    end
    on_intel do
      ${source("darwin-x64")}
    end
  end

  on_linux do
    depends_on arch: :x86_64

    on_intel do
      ${source("linux-x64")}
    end
  end

  def install
    # The executable loads its browser and platform assets from its own directory.
    libexec.install "dist"
    bin.write_exec_script libexec/"dist/agentsims"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/agentsims --version").strip
  end
end
`;
}

export function writeRelease(version: string, directory: string): ReleaseMetadata {
	if (!/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(version))
		throw new Error("The release version must have the form 1.2.3.");
	const sha256 = (file: string) =>
		createHash("sha256")
			.update(readFileSync(join(directory, file)))
			.digest("hex");
	const metadata: ReleaseMetadata = {
		schemaVersion: 1,
		version,
		repository: REPOSITORY,
		artifacts: Object.fromEntries(
			RUNTIME_TARGETS.map((target) => {
				const file = runtimeArchiveName(target);
				return [target, { file, sha256: sha256(file) }];
			}),
		) as ReleaseMetadata["artifacts"],
	};
	const checksums = [
		...RUNTIME_TARGETS.map((target) => metadata.artifacts[target]),
		{ file: CHATGPT_ARCHIVE_NAME, sha256: sha256(CHATGPT_ARCHIVE_NAME) },
	];
	writeFileSync(
		join(directory, "SHA256SUMS"),
		checksums.map(({ file, sha256 }) => `${sha256}  ${file}\n`).join(""),
	);
	writeFileSync(
		join(directory, "release-metadata.json"),
		JSON.stringify(metadata, null, 2) + "\n",
	);
	writeFileSync(
		join(directory, "install.sh"),
		readFileSync(new URL("./install.sh", import.meta.url), "utf8").replaceAll(
			"__AGENTSIMS_RELEASE_VERSION__",
			version,
		),
	);
	writeFileSync(join(directory, "agentsims.rb"), formula(metadata));
	return metadata;
}

if (import.meta.main) {
	const [version, directory] = process.argv.slice(2);
	if (!version || !directory)
		throw new Error("Usage: bun scripts/release.ts <version> <directory>");
	writeRelease(version, resolve(directory));
}
